
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("552b88b5-71e3-4735-b4df-049f64424f00")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("dbBoschModel", "FK_dni_cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(C_Cliente), "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Factura), True)> 
<Assembly: EdmRelationshipAttribute("dbBoschModel", "FK_id_factura", "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Factura), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)> 
<Assembly: EdmRelationshipAttribute("dbBoschModel", "FK_id_producto", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Producto), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)> 
<Assembly: EdmRelationshipAttribute("dbBoschModel", "FK_id_tipoProducto", "TipoProducto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(TipoProducto), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Producto), True)> 

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Partial Public Class dbBoschEntities
    Inherits ObjectContext

#Region "Constructors"

    ''' <summary>
    ''' Initializes a new dbBoschEntities object using the connection string found in the 'dbBoschEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=dbBoschEntities", "dbBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dbBoschEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "dbBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dbBoschEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "dbBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = True
        OnContextCreated()
    End Sub

#End Region

#Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

#End Region

#Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cliente() As ObjectSet(Of C_Cliente)
        Get
            If (_Cliente Is Nothing) Then
                _Cliente = MyBase.CreateObjectSet(Of C_Cliente)("Cliente")
            End If
            Return _Cliente
        End Get
    End Property

    Private _Cliente As ObjectSet(Of C_Cliente)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Detalle() As ObjectSet(Of Detalle)
        Get
            If (_Detalle Is Nothing) Then
                _Detalle = MyBase.CreateObjectSet(Of Detalle)("Detalle")
            End If
            Return _Detalle
        End Get
    End Property

    Private _Detalle As ObjectSet(Of Detalle)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Factura() As ObjectSet(Of Factura)
        Get
            If (_Factura Is Nothing) Then
                _Factura = MyBase.CreateObjectSet(Of Factura)("Factura")
            End If
            Return _Factura
        End Get
    End Property

    Private _Factura As ObjectSet(Of Factura)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Producto() As ObjectSet(Of Producto)
        Get
            If (_Producto Is Nothing) Then
                _Producto = MyBase.CreateObjectSet(Of Producto)("Producto")
            End If
            Return _Producto
        End Get
    End Property

    Private _Producto As ObjectSet(Of Producto)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TipoProducto() As ObjectSet(Of TipoProducto)
        Get
            If (_TipoProducto Is Nothing) Then
                _TipoProducto = MyBase.CreateObjectSet(Of TipoProducto)("TipoProducto")
            End If
            Return _TipoProducto
        End Get
    End Property

    Private _TipoProducto As ObjectSet(Of TipoProducto)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Usuario() As ObjectSet(Of C_Usuario)
        Get
            If (_Usuario Is Nothing) Then
                _Usuario = MyBase.CreateObjectSet(Of C_Usuario)("Usuario")
            End If
            Return _Usuario
        End Get
    End Property

    Private _Usuario As ObjectSet(Of C_Usuario)

#End Region
#Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCliente(ByVal cliente As C_Cliente)
        MyBase.AddObject("Cliente", cliente)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Detalle EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDetalle(ByVal detalle As Detalle)
        MyBase.AddObject("Detalle", detalle)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Factura EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToFactura(ByVal factura As Factura)
        MyBase.AddObject("Factura", factura)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Producto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducto(ByVal producto As Producto)
        MyBase.AddObject("Producto", producto)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TipoProducto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTipoProducto(ByVal tipoProducto As TipoProducto)
        MyBase.AddObject("TipoProducto", tipoProducto)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsuario(ByVal usuario As C_Usuario)
        MyBase.AddObject("Usuario", usuario)
    End Sub

#End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="Cliente")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class C_Cliente
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Cliente object.
    ''' </summary>
    ''' <param name="dni_cliente">Initial value of the dni_cliente property.</param>
    Public Shared Function CreateCliente(ByVal dni_cliente As Global.System.Int32) As C_Cliente
        Dim cliente As C_Cliente = New C_Cliente
        cliente.dni_cliente = dni_cliente
        Return cliente
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property dni_cliente() As Global.System.Int32
        Get
            Return _dni_cliente
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_dni_cliente <> Value) Then
                Ondni_clienteChanging(value)
                ReportPropertyChanging("dni_cliente")
                _dni_cliente = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("dni_cliente")
                Ondni_clienteChanged()
            End If
        End Set
    End Property

    Private _dni_cliente As Global.System.Int32
    Partial Private Sub Ondni_clienteChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Ondni_clienteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set(ByVal value As Global.System.String)
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Partial Private Sub OnnombreChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set(ByVal value As Global.System.String)
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Partial Private Sub OnapellidoChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property direccion() As Global.System.String
        Get
            Return _direccion
        End Get
        Set(ByVal value As Global.System.String)
            OndireccionChanging(value)
            ReportPropertyChanging("direccion")
            _direccion = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("direccion")
            OndireccionChanged()
        End Set
    End Property

    Private _direccion As Global.System.String
    Partial Private Sub OndireccionChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OndireccionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property telefono() As Global.System.String
        Get
            Return _telefono
        End Get
        Set(ByVal value As Global.System.String)
            OntelefonoChanging(value)
            ReportPropertyChanging("telefono")
            _telefono = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("telefono")
            OntelefonoChanged()
        End Set
    End Property

    Private _telefono As Global.System.String
    Partial Private Sub OntelefonoChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OntelefonoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property fechaNacimiento() As Global.System.String
        Get
            Return _fechaNacimiento
        End Get
        Set(ByVal value As Global.System.String)
            OnfechaNacimientoChanging(value)
            ReportPropertyChanging("fechaNacimiento")
            _fechaNacimiento = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("fechaNacimiento")
            OnfechaNacimientoChanged()
        End Set
    End Property

    Private _fechaNacimiento As Global.System.String
    Partial Private Sub OnfechaNacimientoChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnfechaNacimientoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property mail() As Global.System.String
        Get
            Return _mail
        End Get
        Set(ByVal value As Global.System.String)
            OnmailChanging(value)
            ReportPropertyChanging("mail")
            _mail = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("mail")
            OnmailChanged()
        End Set
    End Property

    Private _mail As Global.System.String
    Partial Private Sub OnmailChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnmailChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_dni_cliente", "Factura")>
    Public Property Factura() As EntityCollection(Of Factura)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Factura)("dbBoschModel.FK_dni_cliente", "Factura")
        End Get
        Set(ByVal value As EntityCollection(Of Factura))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Factura)("dbBoschModel.FK_dni_cliente", "Factura", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="Detalle")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Detalle
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Detalle object.
    ''' </summary>
    ''' <param name="id_detalle">Initial value of the id_detalle property.</param>
    ''' <param name="id_factura">Initial value of the id_factura property.</param>
    Public Shared Function CreateDetalle(ByVal id_detalle As Global.System.Int32, ByVal id_factura As Global.System.Int32) As Detalle
        Dim detalle As Detalle = New Detalle
        detalle.id_detalle = id_detalle
        detalle.id_factura = id_factura
        Return detalle
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_detalle() As Global.System.Int32
        Get
            Return _id_detalle
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_detalle <> Value) Then
                Onid_detalleChanging(value)
                ReportPropertyChanging("id_detalle")
                _id_detalle = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_detalle")
                Onid_detalleChanged()
            End If
        End Set
    End Property

    Private _id_detalle As Global.System.Int32
    Partial Private Sub Onid_detalleChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_detalleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property cantidad() As Nullable(Of Global.System.Int32)
        Get
            Return _cantidad
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            OncantidadChanging(value)
            ReportPropertyChanging("cantidad")
            _cantidad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cantidad")
            OncantidadChanged()
        End Set
    End Property

    Private _cantidad As Nullable(Of Global.System.Int32)
    Partial Private Sub OncantidadChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub OncantidadChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property precio() As Nullable(Of Global.System.Double)
        Get
            Return _precio
        End Get
        Set(ByVal value As Nullable(Of Global.System.Double))
            OnprecioChanging(value)
            ReportPropertyChanging("precio")
            _precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("precio")
            OnprecioChanged()
        End Set
    End Property

    Private _precio As Nullable(Of Global.System.Double)
    Partial Private Sub OnprecioChanging(ByVal value As Nullable(Of Global.System.Double))
    End Sub

    Partial Private Sub OnprecioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_factura() As Global.System.Int32
        Get
            Return _id_factura
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_factura <> Value) Then
                Onid_facturaChanging(value)
                ReportPropertyChanging("id_factura")
                _id_factura = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_factura")
                Onid_facturaChanged()
            End If
        End Set
    End Property

    Private _id_factura As Global.System.Int32
    Partial Private Sub Onid_facturaChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_facturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property id_producto() As Nullable(Of Global.System.Int32)
        Get
            Return _id_producto
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            Onid_productoChanging(value)
            ReportPropertyChanging("id_producto")
            _id_producto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_producto")
            Onid_productoChanged()
        End Set
    End Property

    Private _id_producto As Nullable(Of Global.System.Int32)
    Partial Private Sub Onid_productoChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub Onid_productoChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_factura", "Factura")>
    Public Property Factura() As Factura
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbBoschModel.FK_id_factura", "Factura").Value
        End Get
        Set(ByVal value As Factura)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbBoschModel.FK_id_factura", "Factura").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property FacturaReference() As EntityReference(Of Factura)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbBoschModel.FK_id_factura", "Factura")
        End Get
        Set(ByVal value As EntityReference(Of Factura))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Factura)("dbBoschModel.FK_id_factura", "Factura", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_producto", "Producto")>
    Public Property Producto() As Producto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbBoschModel.FK_id_producto", "Producto").Value
        End Get
        Set(ByVal value As Producto)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbBoschModel.FK_id_producto", "Producto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductoReference() As EntityReference(Of Producto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbBoschModel.FK_id_producto", "Producto")
        End Get
        Set(ByVal value As EntityReference(Of Producto))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Producto)("dbBoschModel.FK_id_producto", "Producto", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="Factura")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Factura
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Factura object.
    ''' </summary>
    ''' <param name="id_factura">Initial value of the id_factura property.</param>
    Public Shared Function CreateFactura(ByVal id_factura As Global.System.Int32) As Factura
        Dim factura As Factura = New Factura
        factura.id_factura = id_factura
        Return factura
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_factura() As Global.System.Int32
        Get
            Return _id_factura
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_factura <> Value) Then
                Onid_facturaChanging(value)
                ReportPropertyChanging("id_factura")
                _id_factura = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_factura")
                Onid_facturaChanged()
            End If
        End Set
    End Property

    Private _id_factura As Global.System.Int32
    Partial Private Sub Onid_facturaChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_facturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property fecha() As Nullable(Of Global.System.DateTime)
        Get
            Return _fecha
        End Get
        Set(ByVal value As Nullable(Of Global.System.DateTime))
            OnfechaChanging(value)
            ReportPropertyChanging("fecha")
            _fecha = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fecha")
            OnfechaChanged()
        End Set
    End Property

    Private _fecha As Nullable(Of Global.System.DateTime)
    Partial Private Sub OnfechaChanging(ByVal value As Nullable(Of Global.System.DateTime))
    End Sub

    Partial Private Sub OnfechaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property numerofactura() As Nullable(Of Global.System.Int32)
        Get
            Return _numerofactura
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            OnnumerofacturaChanging(value)
            ReportPropertyChanging("numerofactura")
            _numerofactura = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("numerofactura")
            OnnumerofacturaChanged()
        End Set
    End Property

    Private _numerofactura As Nullable(Of Global.System.Int32)
    Partial Private Sub OnnumerofacturaChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub OnnumerofacturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property dni_cliente() As Nullable(Of Global.System.Int32)
        Get
            Return _dni_cliente
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            Ondni_clienteChanging(value)
            ReportPropertyChanging("dni_cliente")
            _dni_cliente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dni_cliente")
            Ondni_clienteChanged()
        End Set
    End Property

    Private _dni_cliente As Nullable(Of Global.System.Int32)
    Partial Private Sub Ondni_clienteChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub Ondni_clienteChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_dni_cliente", "Cliente")>
    Public Property Cliente() As C_Cliente
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of C_Cliente)("dbBoschModel.FK_dni_cliente", "Cliente").Value
        End Get
        Set(ByVal value As C_Cliente)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of C_Cliente)("dbBoschModel.FK_dni_cliente", "Cliente").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ClienteReference() As EntityReference(Of C_Cliente)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of C_Cliente)("dbBoschModel.FK_dni_cliente", "Cliente")
        End Get
        Set(ByVal value As EntityReference(Of C_Cliente))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of C_Cliente)("dbBoschModel.FK_dni_cliente", "Cliente", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_factura", "Detalle")>
    Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("dbBoschModel.FK_id_factura", "Detalle")
        End Get
        Set(ByVal value As EntityCollection(Of Detalle))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("dbBoschModel.FK_id_factura", "Detalle", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="Producto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class Producto
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Producto object.
    ''' </summary>
    ''' <param name="id_producto">Initial value of the id_producto property.</param>
    ''' <param name="nombre">Initial value of the nombre property.</param>
    Public Shared Function CreateProducto(ByVal id_producto As Global.System.Int32, ByVal nombre As Global.System.String) As Producto
        Dim producto As Producto = New Producto
        producto.id_producto = id_producto
        producto.nombre = nombre
        Return producto
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_producto() As Global.System.Int32
        Get
            Return _id_producto
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_producto <> Value) Then
                Onid_productoChanging(value)
                ReportPropertyChanging("id_producto")
                _id_producto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_producto")
                Onid_productoChanged()
            End If
        End Set
    End Property

    Private _id_producto As Global.System.Int32
    Partial Private Sub Onid_productoChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_productoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set(ByVal value As Global.System.String)
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Partial Private Sub OnnombreChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set(ByVal value As Global.System.String)
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Partial Private Sub OndescripcionChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OndescripcionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property precio() As Nullable(Of Global.System.Double)
        Get
            Return _precio
        End Get
        Set(ByVal value As Nullable(Of Global.System.Double))
            OnprecioChanging(value)
            ReportPropertyChanging("precio")
            _precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("precio")
            OnprecioChanged()
        End Set
    End Property

    Private _precio As Nullable(Of Global.System.Double)
    Partial Private Sub OnprecioChanging(ByVal value As Nullable(Of Global.System.Double))
    End Sub

    Partial Private Sub OnprecioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property stock() As Nullable(Of Global.System.Int32)
        Get
            Return _stock
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            OnstockChanging(value)
            ReportPropertyChanging("stock")
            _stock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("stock")
            OnstockChanged()
        End Set
    End Property

    Private _stock As Nullable(Of Global.System.Int32)
    Partial Private Sub OnstockChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub OnstockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property id_tipoProducto() As Nullable(Of Global.System.Int32)
        Get
            Return _id_tipoProducto
        End Get
        Set(ByVal value As Nullable(Of Global.System.Int32))
            Onid_tipoProductoChanging(value)
            ReportPropertyChanging("id_tipoProducto")
            _id_tipoProducto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_tipoProducto")
            Onid_tipoProductoChanged()
        End Set
    End Property

    Private _id_tipoProducto As Nullable(Of Global.System.Int32)
    Partial Private Sub Onid_tipoProductoChanging(ByVal value As Nullable(Of Global.System.Int32))
    End Sub

    Partial Private Sub Onid_tipoProductoChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_producto", "Detalle")>
    Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("dbBoschModel.FK_id_producto", "Detalle")
        End Get
        Set(ByVal value As EntityCollection(Of Detalle))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("dbBoschModel.FK_id_producto", "Detalle", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_tipoProducto", "TipoProducto")>
    Public Property TipoProducto() As TipoProducto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbBoschModel.FK_id_tipoProducto", "TipoProducto").Value
        End Get
        Set(ByVal value As TipoProducto)
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbBoschModel.FK_id_tipoProducto", "TipoProducto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TipoProductoReference() As EntityReference(Of TipoProducto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbBoschModel.FK_id_tipoProducto", "TipoProducto")
        End Get
        Set(ByVal value As EntityReference(Of TipoProducto))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of TipoProducto)("dbBoschModel.FK_id_tipoProducto", "TipoProducto", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="TipoProducto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class TipoProducto
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new TipoProducto object.
    ''' </summary>
    ''' <param name="id_tipoProducto">Initial value of the id_tipoProducto property.</param>
    Public Shared Function CreateTipoProducto(ByVal id_tipoProducto As Global.System.Int32) As TipoProducto
        Dim tipoProducto As TipoProducto = New TipoProducto
        tipoProducto.id_tipoProducto = id_tipoProducto
        Return tipoProducto
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_tipoProducto() As Global.System.Int32
        Get
            Return _id_tipoProducto
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_tipoProducto <> Value) Then
                Onid_tipoProductoChanging(value)
                ReportPropertyChanging("id_tipoProducto")
                _id_tipoProducto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_tipoProducto")
                Onid_tipoProductoChanged()
            End If
        End Set
    End Property

    Private _id_tipoProducto As Global.System.Int32
    Partial Private Sub Onid_tipoProductoChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_tipoProductoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set(ByVal value As Global.System.String)
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Partial Private Sub OndescripcionChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OndescripcionChanged()
    End Sub

#End Region
#Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbBoschModel", "FK_id_tipoProducto", "Producto")>
    Public Property Producto() As EntityCollection(Of Producto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Producto)("dbBoschModel.FK_id_tipoProducto", "Producto")
        End Get
        Set(ByVal value As EntityCollection(Of Producto))
            If (Not value Is Nothing) Then
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Producto)("dbBoschModel.FK_id_tipoProducto", "Producto", value)
            End If
        End Set
    End Property

#End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbBoschModel", Name:="Usuario")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Partial Public Class C_Usuario
    Inherits EntityObject
#Region "Factory Method"

    ''' <summary>
    ''' Create a new Usuario object.
    ''' </summary>
    ''' <param name="id_usuario">Initial value of the id_usuario property.</param>
    Public Shared Function CreateUsuario(ByVal id_usuario As Global.System.Int32) As C_Usuario
        Dim usuario As C_Usuario = New C_Usuario
        usuario.id_usuario = id_usuario
        Return usuario
    End Function

#End Region
#Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False)>
    <DataMemberAttribute()>
    Public Property id_usuario() As Global.System.Int32
        Get
            Return _id_usuario
        End Get
        Set(ByVal value As Global.System.Int32)
            If (_id_usuario <> Value) Then
                Onid_usuarioChanging(value)
                ReportPropertyChanging("id_usuario")
                _id_usuario = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_usuario")
                Onid_usuarioChanged()
            End If
        End Set
    End Property

    Private _id_usuario As Global.System.Int32
    Partial Private Sub Onid_usuarioChanging(ByVal value As Global.System.Int32)
    End Sub

    Partial Private Sub Onid_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.String
        Get
            Return _id
        End Get
        Set(ByVal value As Global.System.String)
            OnidChanging(value)
            ReportPropertyChanging("id")
            _id = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("id")
            OnidChanged()
        End Set
    End Property

    Private _id As Global.System.String
    Partial Private Sub OnidChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property pass() As Global.System.String
        Get
            Return _pass
        End Get
        Set(ByVal value As Global.System.String)
            OnpassChanging(value)
            ReportPropertyChanging("pass")
            _pass = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("pass")
            OnpassChanged()
        End Set
    End Property

    Private _pass As Global.System.String
    Partial Private Sub OnpassChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnpassChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set(ByVal value As Global.System.String)
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Partial Private Sub OnnombreChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set(ByVal value As Global.System.String)
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Partial Private Sub OnapellidoChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property tipoUsuario() As Global.System.String
        Get
            Return _tipoUsuario
        End Get
        Set(ByVal value As Global.System.String)
            OntipoUsuarioChanging(value)
            ReportPropertyChanging("tipoUsuario")
            _tipoUsuario = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("tipoUsuario")
            OntipoUsuarioChanged()
        End Set
    End Property

    Private _tipoUsuario As Global.System.String
    Partial Private Sub OntipoUsuarioChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OntipoUsuarioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property fechaNacimiento() As Global.System.String
        Get
            Return _fechaNacimiento
        End Get
        Set(ByVal value As Global.System.String)
            OnfechaNacimientoChanging(value)
            ReportPropertyChanging("fechaNacimiento")
            _fechaNacimiento = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("fechaNacimiento")
            OnfechaNacimientoChanged()
        End Set
    End Property

    Private _fechaNacimiento As Global.System.String
    Partial Private Sub OnfechaNacimientoChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnfechaNacimientoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property mail() As Global.System.String
        Get
            Return _mail
        End Get
        Set(ByVal value As Global.System.String)
            OnmailChanging(value)
            ReportPropertyChanging("mail")
            _mail = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("mail")
            OnmailChanged()
        End Set
    End Property

    Private _mail As Global.System.String
    Partial Private Sub OnmailChanging(ByVal value As Global.System.String)
    End Sub

    Partial Private Sub OnmailChanged()
    End Sub

#End Region
End Class

#End Region

