
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("9868a27e-afe8-4fad-85b5-e4ef19259662")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("dbPruebaBoschModel", "FK_dni_cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Cliente), "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Factura), True)>
<Assembly: EdmRelationshipAttribute("dbPruebaBoschModel", "FK_id_factura", "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Factura), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)>
<Assembly: EdmRelationshipAttribute("dbPruebaBoschModel", "FK_id_producto", "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Producto), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Detalle), True)>
<Assembly: EdmRelationshipAttribute("dbPruebaBoschModel", "FK_id_tipoProducto", "TipoProducto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(TipoProducto), "Producto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Producto), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class dbPruebaBoschEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new dbPruebaBoschEntities object using the connection string found in the 'dbPruebaBoschEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=dbPruebaBoschEntities", "dbPruebaBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dbPruebaBoschEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "dbPruebaBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new dbPruebaBoschEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "dbPruebaBoschEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Cliente() As ObjectSet(Of Cliente)
        Get
            If (_Cliente Is Nothing) Then
                _Cliente = MyBase.CreateObjectSet(Of Cliente)("Cliente")
            End If
            Return _Cliente
        End Get
    End Property

    Private _Cliente As ObjectSet(Of Cliente)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Detalle() As ObjectSet(Of Detalle)
        Get
            If (_Detalle Is Nothing) Then
                _Detalle = MyBase.CreateObjectSet(Of Detalle)("Detalle")
            End If
            Return _Detalle
        End Get
    End Property

    Private _Detalle As ObjectSet(Of Detalle)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Factura() As ObjectSet(Of Factura)
        Get
            If (_Factura Is Nothing) Then
                _Factura = MyBase.CreateObjectSet(Of Factura)("Factura")
            End If
            Return _Factura
        End Get
    End Property

    Private _Factura As ObjectSet(Of Factura)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Producto() As ObjectSet(Of Producto)
        Get
            If (_Producto Is Nothing) Then
                _Producto = MyBase.CreateObjectSet(Of Producto)("Producto")
            End If
            Return _Producto
        End Get
    End Property

    Private _Producto As ObjectSet(Of Producto)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property TipoProducto() As ObjectSet(Of TipoProducto)
        Get
            If (_TipoProducto Is Nothing) Then
                _TipoProducto = MyBase.CreateObjectSet(Of TipoProducto)("TipoProducto")
            End If
            Return _TipoProducto
        End Get
    End Property

    Private _TipoProducto As ObjectSet(Of TipoProducto)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Usuario() As ObjectSet(Of Usuario)
        Get
            If (_Usuario Is Nothing) Then
                _Usuario = MyBase.CreateObjectSet(Of Usuario)("Usuario")
            End If
            Return _Usuario
        End Get
    End Property

    Private _Usuario As ObjectSet(Of Usuario)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Cliente EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCliente(ByVal cliente As Cliente)
        MyBase.AddObject("Cliente", cliente)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Detalle EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDetalle(ByVal detalle As Detalle)
        MyBase.AddObject("Detalle", detalle)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Factura EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToFactura(ByVal factura As Factura)
        MyBase.AddObject("Factura", factura)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Producto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducto(ByVal producto As Producto)
        MyBase.AddObject("Producto", producto)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the TipoProducto EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToTipoProducto(ByVal tipoProducto As TipoProducto)
        MyBase.AddObject("TipoProducto", tipoProducto)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsuario(ByVal usuario As Usuario)
        MyBase.AddObject("Usuario", usuario)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="Cliente")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Cliente
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Cliente object.
    ''' </summary>
    ''' <param name="dni_cliente">Initial value of the dni_cliente property.</param>
    Public Shared Function CreateCliente(dni_cliente As Global.System.Int32) As Cliente
        Dim cliente as Cliente = New Cliente
        cliente.dni_cliente = dni_cliente
        Return cliente
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property dni_cliente() As Global.System.Int32
        Get
            Return _dni_cliente
        End Get
        Set
            If (_dni_cliente <> Value) Then
                Ondni_clienteChanging(value)
                ReportPropertyChanging("dni_cliente")
                _dni_cliente = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("dni_cliente")
                Ondni_clienteChanged()
            End If
        End Set
    End Property

    Private _dni_cliente As Global.System.Int32
    Private Partial Sub Ondni_clienteChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondni_clienteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Private Partial Sub OnapellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property direccion() As Global.System.String
        Get
            Return _direccion
        End Get
        Set
            OndireccionChanging(value)
            ReportPropertyChanging("direccion")
            _direccion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("direccion")
            OndireccionChanged()
        End Set
    End Property

    Private _direccion As Global.System.String
    Private Partial Sub OndireccionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndireccionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property telefono() As Global.System.String
        Get
            Return _telefono
        End Get
        Set
            OntelefonoChanging(value)
            ReportPropertyChanging("telefono")
            _telefono = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("telefono")
            OntelefonoChanged()
        End Set
    End Property

    Private _telefono As Global.System.String
    Private Partial Sub OntelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntelefonoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fechaNacimiento() As Global.System.String
        Get
            Return _fechaNacimiento
        End Get
        Set
            OnfechaNacimientoChanging(value)
            ReportPropertyChanging("fechaNacimiento")
            _fechaNacimiento = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fechaNacimiento")
            OnfechaNacimientoChanged()
        End Set
    End Property

    Private _fechaNacimiento As Global.System.String
    Private Partial Sub OnfechaNacimientoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfechaNacimientoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property mail() As Global.System.String
        Get
            Return _mail
        End Get
        Set
            OnmailChanging(value)
            ReportPropertyChanging("mail")
            _mail = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("mail")
            OnmailChanged()
        End Set
    End Property

    Private _mail As Global.System.String
    Private Partial Sub OnmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmailChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_dni_cliente", "Factura")>
     Public Property Factura() As EntityCollection(Of Factura)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Factura)("dbPruebaBoschModel.FK_dni_cliente", "Factura")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Factura)("dbPruebaBoschModel.FK_dni_cliente", "Factura", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="Detalle")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Detalle
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Detalle object.
    ''' </summary>
    ''' <param name="id_detalle">Initial value of the id_detalle property.</param>
    ''' <param name="id_factura">Initial value of the id_factura property.</param>
    Public Shared Function CreateDetalle(id_detalle As Global.System.Int32, id_factura As Global.System.Int32) As Detalle
        Dim detalle as Detalle = New Detalle
        detalle.id_detalle = id_detalle
        detalle.id_factura = id_factura
        Return detalle
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_detalle() As Global.System.Int32
        Get
            Return _id_detalle
        End Get
        Set
            If (_id_detalle <> Value) Then
                Onid_detalleChanging(value)
                ReportPropertyChanging("id_detalle")
                _id_detalle = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_detalle")
                Onid_detalleChanged()
            End If
        End Set
    End Property

    Private _id_detalle As Global.System.Int32
    Private Partial Sub Onid_detalleChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_detalleChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property cantidad() As Nullable(Of Global.System.Int32)
        Get
            Return _cantidad
        End Get
        Set
            OncantidadChanging(value)
            ReportPropertyChanging("cantidad")
            _cantidad = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("cantidad")
            OncantidadChanged()
        End Set
    End Property

    Private _cantidad As Nullable(Of Global.System.Int32)
    Private Partial Sub OncantidadChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OncantidadChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property precio() As Nullable(Of Global.System.Double)
        Get
            Return _precio
        End Get
        Set
            OnprecioChanging(value)
            ReportPropertyChanging("precio")
            _precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("precio")
            OnprecioChanged()
        End Set
    End Property

    Private _precio As Nullable(Of Global.System.Double)
    Private Partial Sub OnprecioChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnprecioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_factura() As Global.System.Int32
        Get
            Return _id_factura
        End Get
        Set
            If (_id_factura <> Value) Then
                Onid_facturaChanging(value)
                ReportPropertyChanging("id_factura")
                _id_factura = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_factura")
                Onid_facturaChanged()
            End If
        End Set
    End Property

    Private _id_factura As Global.System.Int32
    Private Partial Sub Onid_facturaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_facturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_producto() As Nullable(Of Global.System.Int32)
        Get
            Return _id_producto
        End Get
        Set
            Onid_productoChanging(value)
            ReportPropertyChanging("id_producto")
            _id_producto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_producto")
            Onid_productoChanged()
        End Set
    End Property

    Private _id_producto As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_productoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_productoChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_factura", "Factura")>
    Public Property Factura() As Factura
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbPruebaBoschModel.FK_id_factura", "Factura").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbPruebaBoschModel.FK_id_factura", "Factura").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property FacturaReference() As EntityReference(Of Factura)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Factura)("dbPruebaBoschModel.FK_id_factura", "Factura")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Factura)("dbPruebaBoschModel.FK_id_factura", "Factura", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_producto", "Producto")>
    Public Property Producto() As Producto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbPruebaBoschModel.FK_id_producto", "Producto").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbPruebaBoschModel.FK_id_producto", "Producto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductoReference() As EntityReference(Of Producto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Producto)("dbPruebaBoschModel.FK_id_producto", "Producto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Producto)("dbPruebaBoschModel.FK_id_producto", "Producto", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="Factura")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Factura
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Factura object.
    ''' </summary>
    ''' <param name="id_factura">Initial value of the id_factura property.</param>
    Public Shared Function CreateFactura(id_factura As Global.System.Int32) As Factura
        Dim factura as Factura = New Factura
        factura.id_factura = id_factura
        Return factura
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_factura() As Global.System.Int32
        Get
            Return _id_factura
        End Get
        Set
            If (_id_factura <> Value) Then
                Onid_facturaChanging(value)
                ReportPropertyChanging("id_factura")
                _id_factura = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_factura")
                Onid_facturaChanged()
            End If
        End Set
    End Property

    Private _id_factura As Global.System.Int32
    Private Partial Sub Onid_facturaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_facturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fecha() As Nullable(Of Global.System.DateTime)
        Get
            Return _fecha
        End Get
        Set
            OnfechaChanging(value)
            ReportPropertyChanging("fecha")
            _fecha = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("fecha")
            OnfechaChanged()
        End Set
    End Property

    Private _fecha As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnfechaChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnfechaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property numerofactura() As Nullable(Of Global.System.Int32)
        Get
            Return _numerofactura
        End Get
        Set
            OnnumerofacturaChanging(value)
            ReportPropertyChanging("numerofactura")
            _numerofactura = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("numerofactura")
            OnnumerofacturaChanged()
        End Set
    End Property

    Private _numerofactura As Nullable(Of Global.System.Int32)
    Private Partial Sub OnnumerofacturaChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnnumerofacturaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property dni_cliente() As Nullable(Of Global.System.Int32)
        Get
            Return _dni_cliente
        End Get
        Set
            Ondni_clienteChanging(value)
            ReportPropertyChanging("dni_cliente")
            _dni_cliente = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("dni_cliente")
            Ondni_clienteChanged()
        End Set
    End Property

    Private _dni_cliente As Nullable(Of Global.System.Int32)
    Private Partial Sub Ondni_clienteChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Ondni_clienteChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_dni_cliente", "Cliente")>
    Public Property Cliente() As Cliente
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("dbPruebaBoschModel.FK_dni_cliente", "Cliente").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("dbPruebaBoschModel.FK_dni_cliente", "Cliente").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ClienteReference() As EntityReference(Of Cliente)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Cliente)("dbPruebaBoschModel.FK_dni_cliente", "Cliente")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Cliente)("dbPruebaBoschModel.FK_dni_cliente", "Cliente", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_factura", "Detalle")>
     Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("dbPruebaBoschModel.FK_id_factura", "Detalle")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("dbPruebaBoschModel.FK_id_factura", "Detalle", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="Producto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Producto
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Producto object.
    ''' </summary>
    ''' <param name="id_producto">Initial value of the id_producto property.</param>
    ''' <param name="nombre">Initial value of the nombre property.</param>
    Public Shared Function CreateProducto(id_producto As Global.System.Int32, nombre As Global.System.String) As Producto
        Dim producto as Producto = New Producto
        producto.id_producto = id_producto
        producto.nombre = nombre
        Return producto
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_producto() As Global.System.Int32
        Get
            Return _id_producto
        End Get
        Set
            If (_id_producto <> Value) Then
                Onid_productoChanging(value)
                ReportPropertyChanging("id_producto")
                _id_producto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_producto")
                Onid_productoChanged()
            End If
        End Set
    End Property

    Private _id_producto As Global.System.Int32
    Private Partial Sub Onid_productoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_productoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Private Partial Sub OndescripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescripcionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property precio() As Nullable(Of Global.System.Double)
        Get
            Return _precio
        End Get
        Set
            OnprecioChanging(value)
            ReportPropertyChanging("precio")
            _precio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("precio")
            OnprecioChanged()
        End Set
    End Property

    Private _precio As Nullable(Of Global.System.Double)
    Private Partial Sub OnprecioChanging(value As Nullable(Of Global.System.Double))
    End Sub

    Private Partial Sub OnprecioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property stock() As Nullable(Of Global.System.Int32)
        Get
            Return _stock
        End Get
        Set
            OnstockChanging(value)
            ReportPropertyChanging("stock")
            _stock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("stock")
            OnstockChanged()
        End Set
    End Property

    Private _stock As Nullable(Of Global.System.Int32)
    Private Partial Sub OnstockChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnstockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id_tipoProducto() As Nullable(Of Global.System.Int32)
        Get
            Return _id_tipoProducto
        End Get
        Set
            Onid_tipoProductoChanging(value)
            ReportPropertyChanging("id_tipoProducto")
            _id_tipoProducto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("id_tipoProducto")
            Onid_tipoProductoChanged()
        End Set
    End Property

    Private _id_tipoProducto As Nullable(Of Global.System.Int32)
    Private Partial Sub Onid_tipoProductoChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub Onid_tipoProductoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ruta_img() As Global.System.String
        Get
            Return _ruta_img
        End Get
        Set
            Onruta_imgChanging(value)
            ReportPropertyChanging("ruta_img")
            _ruta_img = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ruta_img")
            Onruta_imgChanged()
        End Set
    End Property

    Private _ruta_img As Global.System.String
    Private Partial Sub Onruta_imgChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onruta_imgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_producto", "Detalle")>
     Public Property Detalle() As EntityCollection(Of Detalle)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Detalle)("dbPruebaBoschModel.FK_id_producto", "Detalle")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Detalle)("dbPruebaBoschModel.FK_id_producto", "Detalle", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_tipoProducto", "TipoProducto")>
    Public Property TipoProducto() As TipoProducto
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbPruebaBoschModel.FK_id_tipoProducto", "TipoProducto").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbPruebaBoschModel.FK_id_tipoProducto", "TipoProducto").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property TipoProductoReference() As EntityReference(Of TipoProducto)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of TipoProducto)("dbPruebaBoschModel.FK_id_tipoProducto", "TipoProducto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of TipoProducto)("dbPruebaBoschModel.FK_id_tipoProducto", "TipoProducto", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="TipoProducto")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class TipoProducto
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new TipoProducto object.
    ''' </summary>
    ''' <param name="id_tipoProducto">Initial value of the id_tipoProducto property.</param>
    Public Shared Function CreateTipoProducto(id_tipoProducto As Global.System.Int32) As TipoProducto
        Dim tipoProducto as TipoProducto = New TipoProducto
        tipoProducto.id_tipoProducto = id_tipoProducto
        Return tipoProducto
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_tipoProducto() As Global.System.Int32
        Get
            Return _id_tipoProducto
        End Get
        Set
            If (_id_tipoProducto <> Value) Then
                Onid_tipoProductoChanging(value)
                ReportPropertyChanging("id_tipoProducto")
                _id_tipoProducto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_tipoProducto")
                Onid_tipoProductoChanged()
            End If
        End Set
    End Property

    Private _id_tipoProducto As Global.System.Int32
    Private Partial Sub Onid_tipoProductoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_tipoProductoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property descripcion() As Global.System.String
        Get
            Return _descripcion
        End Get
        Set
            OndescripcionChanging(value)
            ReportPropertyChanging("descripcion")
            _descripcion = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("descripcion")
            OndescripcionChanged()
        End Set
    End Property

    Private _descripcion As Global.System.String
    Private Partial Sub OndescripcionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OndescripcionChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("dbPruebaBoschModel", "FK_id_tipoProducto", "Producto")>
     Public Property Producto() As EntityCollection(Of Producto)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Producto)("dbPruebaBoschModel.FK_id_tipoProducto", "Producto")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Producto)("dbPruebaBoschModel.FK_id_tipoProducto", "Producto", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="dbPruebaBoschModel", Name:="Usuario")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Usuario
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Usuario object.
    ''' </summary>
    ''' <param name="id_usuario">Initial value of the id_usuario property.</param>
    Public Shared Function CreateUsuario(id_usuario As Global.System.Int32) As Usuario
        Dim usuario as Usuario = New Usuario
        usuario.id_usuario = id_usuario
        Return usuario
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id_usuario() As Global.System.Int32
        Get
            Return _id_usuario
        End Get
        Set
            If (_id_usuario <> Value) Then
                Onid_usuarioChanging(value)
                ReportPropertyChanging("id_usuario")
                _id_usuario = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id_usuario")
                Onid_usuarioChanged()
            End If
        End Set
    End Property

    Private _id_usuario As Global.System.Int32
    Private Partial Sub Onid_usuarioChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onid_usuarioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.String
        Get
            Return _id
        End Get
        Set
            OnidChanging(value)
            ReportPropertyChanging("id")
            _id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("id")
            OnidChanged()
        End Set
    End Property

    Private _id As Global.System.String
    Private Partial Sub OnidChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property pass() As Global.System.String
        Get
            Return _pass
        End Get
        Set
            OnpassChanging(value)
            ReportPropertyChanging("pass")
            _pass = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("pass")
            OnpassChanged()
        End Set
    End Property

    Private _pass As Global.System.String
    Private Partial Sub OnpassChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpassChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property nombre() As Global.System.String
        Get
            Return _nombre
        End Get
        Set
            OnnombreChanging(value)
            ReportPropertyChanging("nombre")
            _nombre = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("nombre")
            OnnombreChanged()
        End Set
    End Property

    Private _nombre As Global.System.String
    Private Partial Sub OnnombreChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnombreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property apellido() As Global.System.String
        Get
            Return _apellido
        End Get
        Set
            OnapellidoChanging(value)
            ReportPropertyChanging("apellido")
            _apellido = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("apellido")
            OnapellidoChanged()
        End Set
    End Property

    Private _apellido As Global.System.String
    Private Partial Sub OnapellidoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnapellidoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property tipoUsuario() As Global.System.String
        Get
            Return _tipoUsuario
        End Get
        Set
            OntipoUsuarioChanging(value)
            ReportPropertyChanging("tipoUsuario")
            _tipoUsuario = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("tipoUsuario")
            OntipoUsuarioChanged()
        End Set
    End Property

    Private _tipoUsuario As Global.System.String
    Private Partial Sub OntipoUsuarioChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OntipoUsuarioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property fechaNacimiento() As Global.System.String
        Get
            Return _fechaNacimiento
        End Get
        Set
            OnfechaNacimientoChanging(value)
            ReportPropertyChanging("fechaNacimiento")
            _fechaNacimiento = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("fechaNacimiento")
            OnfechaNacimientoChanged()
        End Set
    End Property

    Private _fechaNacimiento As Global.System.String
    Private Partial Sub OnfechaNacimientoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnfechaNacimientoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property mail() As Global.System.String
        Get
            Return _mail
        End Get
        Set
            OnmailChanging(value)
            ReportPropertyChanging("mail")
            _mail = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("mail")
            OnmailChanged()
        End Set
    End Property

    Private _mail As Global.System.String
    Private Partial Sub OnmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnmailChanged()
    End Sub

    #End Region

End Class

#End Region


